name: securify
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  get: ^4.6.6
  firebase_database: ^11.0.1
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  pdf: ^3.10.8
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
